services:

  postgres:
    image: postgres:17
    container_name: finflow-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: finflow
      POSTGRES_USER: finflow
      POSTGRES_PASSWORD: finflow_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: